services:
  - type: web
    name: holiday-calendar-backend
    env: go
    region: oregon
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
